name: provider_dio
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-66.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.6
  get: ^4.6.5
  uuid: ^3.0.6
  mobx: ^2.1.0
  intl: ^0.18.0
  get_it: ^7.2.0
  provider: ^6.0.3
  geolocator: ^9.0.2
  share_plus: ^4.4.0
  battery_plus: ^2.2.1
  image_picker: ^0.8.6
  google_fonts: ^4.0.4
  url_launcher: ^6.1.6
  brasil_fields: ^1.6.0
  gallery_saver: ^2.3.2
  image_cropper: ^3.0.0
  firebase_core: ^1.24.0
  auto_size_text: ^3.0.0
  flutter_mobx: ^2.0.6+4
  path_provider: ^2.0.11
  cloud_firestore: ^3.5.1
  cupertino_icons: ^1.0.2
  qr_code_scanner: ^1.0.1
  device_info_plus: ^5.0.1
  easy_localization: ^3.0.1
  animated_text_kit: ^4.2.2
  connectivity_plus: ^2.3.9
  percent_indicator: ^4.2.2
  firebase_analytics: ^9.3.8
  convex_bottom_bar: ^3.1.0+1
  firebase_messaging: ^13.1.0
  package_info_plus: ^1.4.3+1
  firebase_crashlytics: ^2.9.0
  font_awesome_flutter: ^10.2.1
  flutter_launcher_icons: ^0.13.1
  firebase_remote_config: ^2.0.20
  

dev_dependencies:
  build_runner: ^2.2.1
  mobx_codegen: ^2.0.7+3
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true